## Indexación en *arrays* unidimensionales

Como ya hemos dicho, la indexación se utiliza para acceder y manipular elementos individuales o grupos de elementos en un array. En NumPy, la indexación se realiza utilizando corchetes `[]`, al igual que hacíamos en listas. 

```python
array[i]
# donde i es el índice del elemento al que queremos acceder
```


In [1]:
# antes de empezar importamos la librería de NumPy para poder trabajar con todos sus métodos. 
import numpy as np

In [2]:
# Imaginemos que tenemos el siguiente array unidimensional con 15 elementos
## en nuestro array

unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos acceder al primer elemento de nuestro array
print("\n---------------------------\n")
print(f"El primer elemento de nuestro array es: \n {unidimensional[0]}")

El array unidimensional que tenemos es: 
 [0.68816282 0.75699888 0.73951619 0.72062798 0.36631024 0.69022652
 0.64569782 0.86142009 0.09274719 0.33429435 0.20616209 0.83456783
 0.81800957 0.69571302 0.9652854 ]

---------------------------

El primer elemento de nuestro array es: 
 0.6881628205538739


Bien! en caso de querer obtener o acceder a los ultimos 3 elementos podriamos hacerlo de la misma forma que haciamos con las listas.

In [3]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")


# si queremos acceder a los tres últimos elementos:
print("\n---------------------------\n")
print(f"Los tres últimos elementos de nuestro array son: \n {unidimensional[-3:]}")

El array unidimensional que tenemos es: 
 [0.51281085 0.29922045 0.11899954 0.733775   0.54556891 0.87031772
 0.63962754 0.63464007 0.06338086 0.95320301 0.36538146 0.60265059
 0.15901957 0.60926158 0.0424392 ]

---------------------------

Los tres últimos elementos de nuestro array son: 
 [0.15901957 0.60926158 0.0424392 ]


Para una seleccion acotada de elementos, nuevamente lo hacemos de manera similiar que las listas, esta vez para los elementos ubicados desde la posicion 2 (incluido) y la posicion 4 (no incluido), MUCHA ATENCION EN COMO SE SELECCIONAN LOS ELEMENTOS!!

In [4]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# si queremos seleccionar el tercer y cuarto elemento
print("\n---------------------------\n")
print(f"El tercer y cuarto elemento de nuestro array son: \n {unidimensional[2:4]}")


El array unidimensional que tenemos es: 
 [0.52682527 0.65774362 0.41188248 0.0140761  0.28540157 0.89598373
 0.06407263 0.36490472 0.78563872 0.79241556 0.5043285  0.66755705
 0.29026069 0.53887328 0.37207859]

---------------------------

El tercer y cuarto elemento de nuestro array son: 
 [0.41188248 0.0140761 ]


Continuando con la seleccion de elementos, vemos que podemos combinar ya que se nos pide seleccionar todos los elementos desde el inicio hasta la posicion 10 ( recuerden que como queremos la posicion 10, entonces indicamos como fin el 11 quedando de la manera [:11]) y que a su vez deben ser en saltos de a dos posiciones, por lo que la expresion completa sera [:11:2]

In [5]:
unidimensional = np.random.random_sample(15)
print(f"El array unidimensional que tenemos es: \n {unidimensional}")

# los elementos desde el inicio hasta el 10 en saltos de dos en dos
print("\n---------------------------\n")
print(f"Los elementos desde el inicio hasta el 10 de dos en dos son: \n {unidimensional[:11:2]}")



El array unidimensional que tenemos es: 
 [0.61827437 0.61345468 0.194911   0.56746703 0.21700939 0.065374
 0.23208011 0.59312743 0.87354006 0.94587847 0.98565597 0.95881061
 0.15185765 0.24728464 0.60791783]

---------------------------

Los elementos desde el inicio hasta el 10 de dos en dos son: 
 [0.61827437 0.194911   0.21700939 0.23208011 0.87354006 0.98565597]


## Indexación en *arrays* bidimensionales

En el caso de este tipo de *arrays* se acceder a elementos individuales en una matriz bidimensional utilizando la sintaxis `[fila, columna]` entre corchetes.

Los podemos entender como una lista de listas.

```python
array[i,j]
array[i][j]

# 🚨 Las dos lineas anteriores son exactamente lo mismo
# seleccionará el elemento de la fila "i" y columna "j"
```


Donde: 
- `i` --> filas

- `j` --> columnas

In [6]:
# definimos un array bidimensional
# en este caso estamos generando un array de 5 filas y 4 columnas con números aleatorios entre el 0 y el 1
bidimensional = np.random.rand(5, 4)
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# desgranemos la indexación en este tipo de arrays
# si accedemos al elemento 0 del array obtenemos a la fila que queramos de nuestro array

print(f"\nEl primer elemento de nuestro array es: \n {bidimensional[0]}")

El array bidimensional que tenemos es: 
 [[0.42214212 0.74609509 0.87696079 0.04318946]
 [0.13534479 0.54249625 0.77210589 0.94752063]
 [0.32224622 0.23230077 0.55031145 0.93115652]
 [0.89696255 0.54797431 0.61309795 0.96268145]
 [0.58344172 0.20719895 0.13625527 0.99519379]]

El primer elemento de nuestro array es: 
 [0.42214212 0.74609509 0.87696079 0.04318946]


In [7]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# dado el resultado del paso anterior, sigamos buceando en el array, 
# en este caso querremos acceder al primer elemento del resultado anterior
# fijaos como ponemos dos indices, el primero para acceder a las filas 
# y el segundo para acceder a las columnas
# podríamos decir que es como el juego de hundir la flota
print(f"\nEl primer elemento de la primera fila de nuestro array es: \n {bidimensional[0][0]}")
print("\n-------------------------------------\n")
print(f"bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: \n {bidimensional[0,0]}")

El array bidimensional que tenemos es: 
 [[0.42214212 0.74609509 0.87696079 0.04318946]
 [0.13534479 0.54249625 0.77210589 0.94752063]
 [0.32224622 0.23230077 0.55031145 0.93115652]
 [0.89696255 0.54797431 0.61309795 0.96268145]
 [0.58344172 0.20719895 0.13625527 0.99519379]]

El primer elemento de la primera fila de nuestro array es: 
 0.42214212235137805

-------------------------------------

bidimensional[0][0] es exactamente lo mismo que bidimensional[0,0]: 
 0.42214212235137805


In [8]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")
# accedemos a la segunda fila, tercer columna. 
print("\n---------------------------\n")
print(f"El elemento que esta en la 2ª fila y 3ª columna es: \n {bidimensional[1,2]}")


El array bidimensional que tenemos es: 
 [[0.42214212 0.74609509 0.87696079 0.04318946]
 [0.13534479 0.54249625 0.77210589 0.94752063]
 [0.32224622 0.23230077 0.55031145 0.93115652]
 [0.89696255 0.54797431 0.61309795 0.96268145]
 [0.58344172 0.20719895 0.13625527 0.99519379]]

---------------------------

El elemento que esta en la 2ª fila y 3ª columna es: 
 0.7721058931947801


📌 **NOTA** Cuando usamos la siguiente estructura `array[i,j]`: 

- Todo lo que haya antes de la coma se referirá a filas.


- Todo lo que haya después de la coma se referirá a columnas. 

De esta forma, si por ejemplo queremos seleccionar solo las dos primeras filas usaremos la nomenclatura que ya conocemos con los `:`. Si no especificamos nada (o solo ponemos `:`) se entiende que lo queremos todo. Por ejemplo 👇🏽

In [9]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")
# seleccionamos las dos primeras filas, y todas las columnas (no ponemos 
# nada después de la coma). 
print("\n---------------------------\n")
print(f"Las dos primeras filas con todas sus columnas son: \n {bidimensional[:2,:]}")


El array bidimensional que tenemos es: 
 [[0.42214212 0.74609509 0.87696079 0.04318946]
 [0.13534479 0.54249625 0.77210589 0.94752063]
 [0.32224622 0.23230077 0.55031145 0.93115652]
 [0.89696255 0.54797431 0.61309795 0.96268145]
 [0.58344172 0.20719895 0.13625527 0.99519379]]

---------------------------

Las dos primeras filas con todas sus columnas son: 
 [[0.42214212 0.74609509 0.87696079 0.04318946]
 [0.13534479 0.54249625 0.77210589 0.94752063]]


In [10]:
print(f"El array bidimensional que tenemos es: \n {bidimensional}")

# seleccionamos todas las filas y solo las tres últimas columnas
print("\n---------------------------\n")
print(f"Todas las filas y las últimas tres columnas son: \n {bidimensional[:,-3:]}")

El array bidimensional que tenemos es: 
 [[0.42214212 0.74609509 0.87696079 0.04318946]
 [0.13534479 0.54249625 0.77210589 0.94752063]
 [0.32224622 0.23230077 0.55031145 0.93115652]
 [0.89696255 0.54797431 0.61309795 0.96268145]
 [0.58344172 0.20719895 0.13625527 0.99519379]]

---------------------------

Todas las filas y las últimas tres columnas son: 
 [[0.74609509 0.87696079 0.04318946]
 [0.54249625 0.77210589 0.94752063]
 [0.23230077 0.55031145 0.93115652]
 [0.54797431 0.61309795 0.96268145]
 [0.20719895 0.13625527 0.99519379]]


## Indexación en *arrays* tridimensionales

De la misma forma que en los bidimensionales, el los mutidimensionales podemos acceder a sus elementos de dos formas: 

```python
array[i,j,k]
array[i][j][k]
```

- i → *array* al que queremos acceder 


- j → fila de nuestro *array* al que queremos acceder


- k → columna de nuestro *array* al que queremos acceder

    ![3d-array-index.png](https://github.com/Adalab/data_imagenes/blob/main/Modulo-2/NumPy/index_numpy_multidimensional.png?raw=true)

In [11]:
# definimos un array tridimensional
# en este caso estamos creando un array de números enteros entre el 10 y el 100 con
# 2 matrices, 3 filas y 5 columnas
tridimensional = np.random.randint(10,100, (2,3,5))
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# accedemos al primer array y al elemento que está en la fila 2 y la columna 4
print("\n---------------------------\n")
print(f"El elemento de la 1ª matriz, 2ª fila y 4ª columna es : \n {tridimensional[0,1,3]}")

El array multidimensional que tenemos es: 
 [[[58 45 12 78 10]
  [74 70 60 63 91]
  [93 34 50 72 90]]

 [[13 17 26 98 50]
  [33 93 15 91 76]
  [82 29 32 38 35]]]

---------------------------

El elemento de la 1ª matriz, 2ª fila y 4ª columna es : 
 63


In [12]:
print(f"El array multidimensional que tenemos es: \n {tridimensional}")

# primer array primera fila y todas las columnas
print("\n---------------------------\n")
print(f"Los elementos del 1ª matriz, 1ª fila y todas las columnas  : \n {tridimensional[0,0, :]}")


El array multidimensional que tenemos es: 
 [[[58 45 12 78 10]
  [74 70 60 63 91]
  [93 34 50 72 90]]

 [[13 17 26 98 50]
  [33 93 15 91 76]
  [82 29 32 38 35]]]

---------------------------

Los elementos del 1ª matriz, 1ª fila y todas las columnas  : 
 [58 45 12 78 10]


# Ejercicios


1. Crea un *array* unidimensional con 50 elementos con el método que prefieras y extrae: 

    - El primer elemento.


    - Lo elementos que están en posición impar.


    - Los cuatro primeros elementos.


    - Los últimos tres elementos.


    - Los elementos entre el 4 y el 8 (incluido). 

2. Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

    - La primera fila y todas las columnas.


    - Todas las filas pares.


    - La primera columna y todas las filas.


In [24]:
# Ejercicio 1
# Crea un *array* unidimensional con 50 elementos con el método que prefieras
array = np.arange(50)
print(f"El array unidimensional es: \n  {array} \n")

El array unidimensional es: 
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 



In [17]:
# primer elemento
array[0]

0

In [18]:
# Los elementos que están en posición impar.
array[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [20]:
# Los cuatro primeros elementos.
array[:4]

array([0, 1, 2, 3])

In [21]:
# Los últimos tres elementos.
array[-3:]

array([47, 48, 49])

In [22]:
# Los elementos entre el 4 y el 8 (incluido). 
array[4:9]

array([4, 5, 6, 7, 8])

In [26]:
# Ejercicio 2
# Crea un *array* de dos dimensiones de 4 x 5 con el método que prefieras
array2 = np.random.randint(0, 50, (4,5))
print(f"El array bidimensional es: \n  {array2} \n")

El array bidimensional es: 
  [[10 16 25 44  5]
 [36 37 43  0  0]
 [25 46 13 45 23]
 [38 33 39 38  1]] 



In [27]:
# La primera fila y todas las columnas.
array2[0,:]

array([10, 16, 25, 44,  5])

In [28]:
# Todas las filas pares.
array2[::2]

array([[10, 16, 25, 44,  5],
       [25, 46, 13, 45, 23]])

In [29]:
# La primera columna y todas las filas.
array2[:, 0]

array([10, 36, 25, 38])